// https://nuxt.com/docs/api/configuration/nuxt-config
//
// Front store = full SSR for SEO (server renders real HTML + meta per route, so social
// scrapers — FB/LINE/Twitter — that don't run JS still see og:title/description/image).
// URL structure matches legacy RouteConfig.cs 1:1 (indexed by Google at https://www.tfoodies.com).
// Deployed as a Node server (Nitro node-server preset) on Azure Container Apps.
//
// VISUAL FIDELITY (plan §7.1): the legacy main.css + assets are served VERBATIM from
// /public (NOT imported through Vite, so url(../images/...) keeps resolving). Pages/
// components reproduce the exact legacy DOM/classes. jQuery + the original visual plugins
// (slick/owl/bxSlider/slidebars/magnificPopup/sticky/tabber) load at body close, same as
// the legacy _Scripts.cshtml; under SSR they run only after hydration (client), so
// carousels/mobile-menu/lightbox behave identically without touching the server render.
const siteUrl = process.env.NUXT_PUBLIC_SITE_URL || 'https://www.tfoodies.com'

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  ssr: true,

  nitro: {
    preset: 'node-server',
  },

  modules: ['@pinia/nuxt', '@nuxtjs/sitemap', '@nuxtjs/robots'],

  // Shared by @nuxtjs/sitemap, @nuxtjs/robots and useSeo() canonical/og:url.
  site: {
    url: siteUrl,
    name: '食在呼 TFoodies',
  },

  runtimeConfig: {
    public: {
      apiBase: 'http://localhost:7071/api',
      siteUrl,
    },
  },

  // Dynamic content URLs (products / news / recipes / issues / events) are produced at
  // request time by the server route, which queries the Store API.
  sitemap: {
    sources: ['/api/__sitemap-urls'],
    exclude: ['/Member/**', '/Cart', '/Checkout', '/Order/**'],
  },

  // robots.txt is generated by the module (no static /public/robots.txt). Sitemap line is
  // auto-appended from `site.url`.
  robots: {
    disallow: ['/Member/', '/Cart', '/Checkout', '/Order/'],
  },

  app: {
    head: {
      htmlAttrs: { lang: 'zh-Hant-TW' },
      titleTemplate: '%s｜食在呼 TFoodies',
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/content/images/favicon.ico' },
        // Same Google Fonts as legacy _Styles.cshtml.
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=GFS+Didot|Noto+Sans' },
        // Legacy stylesheets, served verbatim from /public/content/styles.
        { rel: 'stylesheet', href: '/content/styles/jquery-confirm.min.css' },
        { rel: 'stylesheet', href: '/content/styles/main.css' },
      ],
      script: [
        // Same load order as legacy _Scripts.cshtml; at body close so the DOM exists.
        { src: '/scripts/vendor.js', tagPosition: 'bodyClose' },
        { src: '/scripts/plugins.js', tagPosition: 'bodyClose' },
        { src: '/scripts/jquery.validate.min.js', tagPosition: 'bodyClose' },
        { src: '/scripts/jquery-confirm.min.js', tagPosition: 'bodyClose' },
        { src: '/scripts/main.js', tagPosition: 'bodyClose' },
      ],
    },
  },
})
