// https://nuxt.com/docs/api/configuration/nuxt-config
//
// Front store = full SSR for SEO (server renders real HTML + meta per route, so social
// scrapers — FB/LINE/Twitter — that don't run JS still see og:title/description/image).
// URL structure matches legacy RouteConfig.cs 1:1 (indexed by Google at https://www.tfoodies.com).
// Deployed as a Node server (Nitro node-server preset) on Azure Container Apps.
//
// VISUAL FIDELITY (plan §7.1): the legacy main.css + assets are served VERBATIM from
// /public (NOT imported through Vite, so url(../images/...) keeps resolving). Pages/
// components reproduce the exact legacy DOM/classes. jQuery + the original visual plugin
// *definitions* (slick/owl/bxSlider/slidebars/magnificPopup/sticky/tabber) load at body
// close (below); they only define plugins and don't touch app DOM. The plugin *init* —
// legacy main.js — is NOT loaded here: its `$(document).ready` races Vue hydration and
// wipes the carousels, so plugins/legacy-effects.client.ts injects it AFTER hydration and
// rebuilds the content sliders on each SPA navigation.
const siteUrl = process.env.NUXT_PUBLIC_SITE_URL || 'https://www.tfoodies.com'

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  ssr: true,

  nitro: {
    preset: 'node-server',
  },

  modules: ['@pinia/nuxt', '@nuxtjs/sitemap', '@nuxtjs/robots'],

  // 文章詳細頁（最新消息/綠誌/小知識/活動花絮）重新設計的共用樣式。
  // 選擇器全部收斂在 .article-detail / .events-detail 命名空間下，不影響 legacy main.css。
  css: ['~/assets/css/article-detail.css'],

  // Shared by @nuxtjs/sitemap, @nuxtjs/robots and useSeo() canonical/og:url.
  site: {
    url: siteUrl,
    name: '食在呼 TFoodies',
  },

  runtimeConfig: {
    public: {
      apiBase: 'http://localhost:7071/api',
      siteUrl,
      // Azure Blob base for product/article images. The API returns bare filenames
      // (legacy schema); pages prepend this exactly as legacy ViewBag.BlobUrl did
      // (`<blob url>/<container>/`). Override per-env via NUXT_PUBLIC_BLOB_URL.
      blobUrl: process.env.NUXT_PUBLIC_BLOB_URL || 'https://weyprous8ed9.blob.core.windows.net/tfoodies/',
    },
  },

  // Personalised, auth-gated pages: render client-side only. Their guard reads the member
  // token from localStorage, which doesn't exist during SSR — server-rendering them would
  // always redirect a logged-in user to /Member/Login on reload. Not indexed anyway (see
  // sitemap/robots below).
  routeRules: {
    '/Member/**': { ssr: false },
  },

  // Dynamic content URLs (products / news / recipes / issues / events) are produced at
  // request time by the server route, which queries the Store API.
  sitemap: {
    sources: ['/api/__sitemap-urls'],
    exclude: ['/Member/**', '/Cart', '/Checkout', '/Order/**'],
  },

  // robots.txt is generated by the module (no static /public/robots.txt). Sitemap line is
  // auto-appended from `site.url`.
  robots: {
    disallow: ['/Member/', '/Cart', '/Checkout', '/Order/'],
  },

  app: {
    head: {
      htmlAttrs: { lang: 'zh-Hant-TW' },
      titleTemplate: '%s｜食在呼 TFoodies',
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/content/images/favicon.ico' },
        // Same Google Fonts as legacy _Styles.cshtml.
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=GFS+Didot|Noto+Sans' },
        // Legacy stylesheets, served verbatim from /public/content/styles.
        { rel: 'stylesheet', href: '/content/styles/jquery-confirm.min.css' },
        { rel: 'stylesheet', href: '/content/styles/main.css' },
      ],
      script: [
        // Same load order as legacy _Scripts.cshtml; at body close so the DOM exists.
        // These only *define* jQuery + the visual plugins (slick/owl/bxSlider/slidebars/sticky…),
        // they don't touch app DOM, so they're safe to load eagerly.
        { src: '/scripts/vendor.js', tagPosition: 'bodyClose' },
        { src: '/scripts/plugins.js', tagPosition: 'bodyClose' },
        { src: '/scripts/jquery.validate.min.js', tagPosition: 'bodyClose' },
        { src: '/scripts/jquery-confirm.min.js', tagPosition: 'bodyClose' },
        // NOTE: main.js (the plugin *initialisation*) is intentionally NOT loaded here — it runs
        // `$(document).ready` which races Vue hydration and wipes the carousels. It is injected
        // after hydration by plugins/legacy-effects.client.ts instead.
      ],
    },
  },
})
