//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brands()
        {
            this.Brandphotos = new HashSet<Brandphotos>();
            this.Products = new HashSet<Products>();
        }
    
        public System.Guid brandid { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public string logo { get; set; }
        public string banner { get; set; }
        public string patternentitle { get; set; }
        public string patternchtitle { get; set; }
        public string patternmemo { get; set; }
        public string patternclass { get; set; }
        public string ilogo { get; set; }
        public string slogan { get; set; }
        public string intro { get; set; }
        public string storybgclass { get; set; }
        public string storyentitle { get; set; }
        public string storychtitle { get; set; }
        public string storymemo { get; set; }
        public string peopletitle { get; set; }
        public string peopleslogan { get; set; }
        public string peoplememo { get; set; }
        public string peoplephoto { get; set; }
        public string keyword { get; set; }
        public string description { get; set; }
        public int sort { get; set; }
        public Nullable<System.Guid> supplierid { get; set; }
        public int isdisplay { get; set; }
        public string parttnervideo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brandphotos> Brandphotos { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
