//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declarationdetails
    {
        public System.Guid declarationdetailid { get; set; }
        public System.Guid declarationid { get; set; }
        public System.Guid orderid { get; set; }
    
        public virtual Declarations Declarations { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
