//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.Eventphotos = new HashSet<Eventphotos>();
        }
    
        public System.Guid eventid { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string intro { get; set; }
        public System.DateTime eventdate { get; set; }
        public string photo { get; set; }
        public string keyword { get; set; }
        public string description { get; set; }
        public System.DateTime createdate { get; set; }
        public string shortener { get; set; }
        public int sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventphotos> Eventphotos { get; set; }
    }
}
