//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenditures()
        {
            this.Expendituredetails = new HashSet<Expendituredetails>();
            this.Outcomes = new HashSet<Outcomes>();
        }
    
        public System.Guid expenditureid { get; set; }
        public Nullable<System.Guid> supplierid { get; set; }
        public string expenditurecode { get; set; }
        public System.DateTime expendituredate { get; set; }
        public int sourcetype { get; set; }
        public Nullable<System.Guid> purchaseid { get; set; }
        public string note { get; set; }
        public int status { get; set; }
        public System.DateTime createdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expendituredetails> Expendituredetails { get; set; }
        public virtual Purchases Purchases { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outcomes> Outcomes { get; set; }
    }
}
