//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicedetails
    {
        public System.Guid invoicedetailid { get; set; }
        public System.Guid invoiceid { get; set; }
        public Nullable<System.Guid> orderid { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> tax { get; set; }
        public string note { get; set; }
        public Nullable<System.Guid> accountingid { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Accountings Accountings { get; set; }
    }
}
