//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Outofnotices = new HashSet<Outofnotices>();
            this.Smsdetails = new HashSet<Smsdetails>();
            this.Products = new HashSet<Products>();
            this.Refounds = new HashSet<Refounds>();
            this.Incomes = new HashSet<Incomes>();
            this.Orders = new HashSet<Orders>();
            this.Returns = new HashSet<Returns>();
            this.Invoices = new HashSet<Invoices>();
        }
    
        public System.Guid memberid { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> zipcodeid { get; set; }
        public string address { get; set; }
        public bool isagent { get; set; }
        public decimal agentdiscount { get; set; }
        public System.DateTime createdate { get; set; }
        public int ismember { get; set; }
        public bool isenable { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string memo { get; set; }
    
        public virtual Zipcodes Zipcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outofnotices> Outofnotices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smsdetails> Smsdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refounds> Refounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incomes> Incomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}
