//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderdetails()
        {
            this.Orderdetailstocks = new HashSet<Orderdetailstocks>();
            this.Returndetails = new HashSet<Returndetails>();
        }
    
        public System.Guid orderdetailid { get; set; }
        public System.Guid orderid { get; set; }
        public System.Guid productid { get; set; }
        public int qty { get; set; }
        public int price { get; set; }
        public int subtotal { get; set; }
        public int status { get; set; }
        public Nullable<int> discount { get; set; }
        public int isgift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetailstocks> Orderdetailstocks { get; set; }
        public virtual Products Products { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returndetails> Returndetails { get; set; }
    }
}
