//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Declarationdetails = new HashSet<Declarationdetails>();
            this.Orderdetails = new HashSet<Orderdetails>();
            this.Returns = new HashSet<Returns>();
            this.Invoicedetails = new HashSet<Invoicedetails>();
        }
    
        public System.Guid orderid { get; set; }
        public System.Guid memberid { get; set; }
        public int ordertype { get; set; }
        public int warehousetypeid { get; set; }
        public Nullable<System.Guid> warehouseid { get; set; }
        public Nullable<System.Guid> logisticid { get; set; }
        public string ordercode { get; set; }
        public System.DateTime orderdate { get; set; }
        public string recivername { get; set; }
        public string recivermobile { get; set; }
        public int reciverzipcodeid { get; set; }
        public string reciveraddress { get; set; }
        public int recivertime { get; set; }
        public int freight { get; set; }
        public Nullable<int> discount { get; set; }
        public int total { get; set; }
        public int paytype { get; set; }
        public int invoicetype { get; set; }
        public string invoicecode { get; set; }
        public int invoicestatus { get; set; }
        public string companytitle { get; set; }
        public string companynumber { get; set; }
        public string codeatm { get; set; }
        public Nullable<System.DateTime> expirepaydate { get; set; }
        public string note { get; set; }
        public int paystatus { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public int deliverstatus { get; set; }
        public Nullable<System.DateTime> deliverdate { get; set; }
        public string trackingnumber { get; set; }
        public string lovecode { get; set; }
        public Nullable<System.Guid> discountid { get; set; }
        public string lastpan4 { get; set; }
        public System.DateTime createdate { get; set; }
        public bool isdeclaration { get; set; }
        public string remark { get; set; }
        public string RID { get; set; }
        public string Click_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Declarationdetails> Declarationdetails { get; set; }
        public virtual Discounts Discounts { get; set; }
        public virtual Logistics Logistics { get; set; }
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetails> Orderdetails { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        public virtual Zipcodes Zipcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoicedetails> Invoicedetails { get; set; }
    }
}
