//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preorderdetails
    {
        public System.Guid preorderdetailid { get; set; }
        public System.Guid preorderid { get; set; }
        public System.Guid productid { get; set; }
        public int qty { get; set; }
        public int price { get; set; }
        public int subtotal { get; set; }
        public int status { get; set; }
    
        public virtual Preorders Preorders { get; set; }
        public virtual Products Products { get; set; }
    }
}
