//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preorders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preorders()
        {
            this.Preorderdetails = new HashSet<Preorderdetails>();
        }
    
        public System.Guid preorderid { get; set; }
        public string preordercode { get; set; }
        public System.DateTime preorderdate { get; set; }
        public string recivername { get; set; }
        public string recivermobile { get; set; }
        public int reciverzipcodeid { get; set; }
        public string reciveraddress { get; set; }
        public int total { get; set; }
        public int paytype { get; set; }
        public int invoicetype { get; set; }
        public string companytitle { get; set; }
        public string companynumber { get; set; }
        public string codeatm { get; set; }
        public Nullable<System.DateTime> expirepaydate { get; set; }
        public int paystatus { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public System.DateTime createdate { get; set; }
        public string reciveremail { get; set; }
        public int recivertime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preorderdetails> Preorderdetails { get; set; }
    }
}
