//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orderdetails = new HashSet<Orderdetails>();
            this.Outofnotices = new HashSet<Outofnotices>();
            this.Preorderdetails = new HashSet<Preorderdetails>();
            this.Productmedias = new HashSet<Productmedias>();
            this.Productphotos = new HashSet<Productphotos>();
            this.Purchasedetails = new HashSet<Purchasedetails>();
            this.Setproducts = new HashSet<Setproducts>();
            this.Setproducts1 = new HashSet<Setproducts>();
            this.Members = new HashSet<Members>();
            this.Tags = new HashSet<Tags>();
            this.Recipes = new HashSet<Recipes>();
            this.Promoteproducts = new HashSet<Promoteproducts>();
            this.Issues = new HashSet<Issues>();
        }
    
        public System.Guid productid { get; set; }
        public System.Guid producttypeid { get; set; }
        public System.Guid brandid { get; set; }
        public string productnum { get; set; }
        public string title { get; set; }
        public string entitle { get; set; }
        public string intro { get; set; }
        public string memo { get; set; }
        public Nullable<int> fixprice { get; set; }
        public int price { get; set; }
        public string capacity { get; set; }
        public string photo { get; set; }
        public int added { get; set; }
        public bool ishot { get; set; }
        public bool isnew { get; set; }
        public bool isdisabled { get; set; }
        public string keyword { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public Nullable<int> conversion { get; set; }
        public Nullable<decimal> weight { get; set; }
        public bool isset { get; set; }
        public bool isgroupbuy { get; set; }
        public int sort { get; set; }
        public System.DateTime createdate { get; set; }
        public string shortener { get; set; }
    
        public virtual Brands Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetails> Orderdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outofnotices> Outofnotices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preorderdetails> Preorderdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productmedias> Productmedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productphotos> Productphotos { get; set; }
        public virtual Producttypes Producttypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchasedetails> Purchasedetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setproducts> Setproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setproducts> Setproducts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Members> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipes> Recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promoteproducts> Promoteproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issues> Issues { get; set; }
    }
}
