//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotes()
        {
            this.Promoteproducts = new HashSet<Promoteproducts>();
        }
    
        public System.Guid promoteid { get; set; }
        public string title { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime expiredate { get; set; }
        public int type { get; set; }
        public decimal discount { get; set; }
        public int sort { get; set; }
        public System.DateTime createdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promoteproducts> Promoteproducts { get; set; }
    }
}
