//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchases()
        {
            this.Purchasedetails = new HashSet<Purchasedetails>();
            this.Expenditures = new HashSet<Expenditures>();
        }
    
        public System.Guid purchaseid { get; set; }
        public System.Guid supplierid { get; set; }
        public string purchasecode { get; set; }
        public System.DateTime purchasedate { get; set; }
        public System.Guid exchangeid { get; set; }
        public Nullable<System.DateTime> etd { get; set; }
        public string payment { get; set; }
        public string deliverterm { get; set; }
        public string note { get; set; }
        public System.DateTime createdate { get; set; }
        public int status { get; set; }
        public bool isexpenditure { get; set; }
    
        public virtual Exchanges Exchanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchasedetails> Purchasedetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditures> Expenditures { get; set; }
    }
}
