//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchasedetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchasedetails()
        {
            this.Stocks = new HashSet<Stocks>();
        }
    
        public System.Guid purchasedetailid { get; set; }
        public System.Guid purchaseid { get; set; }
        public System.Guid productid { get; set; }
        public decimal unitprice { get; set; }
        public int qty { get; set; }
        public decimal subtotal { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stocks> Stocks { get; set; }
        public virtual Products Products { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
