//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Returns()
        {
            this.Refounds = new HashSet<Refounds>();
            this.Returndetails = new HashSet<Returndetails>();
        }
    
        public System.Guid returnid { get; set; }
        public System.Guid memberid { get; set; }
        public System.Guid orderid { get; set; }
        public string returncode { get; set; }
        public System.DateTime returndate { get; set; }
        public int receivestatus { get; set; }
        public Nullable<System.DateTime> receivedate { get; set; }
        public int refundstatus { get; set; }
        public Nullable<System.DateTime> refunddate { get; set; }
        public System.DateTime createdate { get; set; }
        public int warehousestatus { get; set; }
        public Nullable<System.DateTime> warehousesdate { get; set; }
        public string note { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refounds> Refounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returndetails> Returndetails { get; set; }
    }
}
