//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smsdetails
    {
        public System.Guid smsdetailid { get; set; }
        public System.Guid smsid { get; set; }
        public System.Guid memberid { get; set; }
        public Nullable<int> section { get; set; }
        public string msgid { get; set; }
        public string statuscode { get; set; }
        public Nullable<int> accountpoint { get; set; }
        public string duplicate { get; set; }
        public int issend { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Sms Sms { get; set; }
    }
}
