//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stocks()
        {
            this.Warehousestocks = new HashSet<Warehousestocks>();
        }
    
        public System.Guid stockid { get; set; }
        public System.Guid purchasedetailid { get; set; }
        public System.Guid purchaseid { get; set; }
        public int stocktype { get; set; }
        public System.DateTime createdate { get; set; }
        public string barcode { get; set; }
        public string noticenumber { get; set; }
        public string declarationnumber { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<System.DateTime> manufacturedate { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Purchasedetails Purchasedetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehousestocks> Warehousestocks { get; set; }
    }
}
