//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tfoodiesEntities : DbContext
    {
        public tfoodiesEntities()
            : base("name=tfoodiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLims> AdminLims { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Banners> Banners { get; set; }
        public virtual DbSet<Producttypes> Producttypes { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Zipcodes> Zipcodes { get; set; }
        public virtual DbSet<Productphotos> Productphotos { get; set; }
        public virtual DbSet<Issues> Issues { get; set; }
        public virtual DbSet<Recipeingredients> Recipeingredients { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<Recipeseasonings> Recipeseasonings { get; set; }
        public virtual DbSet<Recipesteps> Recipesteps { get; set; }
        public virtual DbSet<Issuemedias> Issuemedias { get; set; }
        public virtual DbSet<Productmedias> Productmedias { get; set; }
        public virtual DbSet<Ordercodes> Ordercodes { get; set; }
        public virtual DbSet<Brandphotos> Brandphotos { get; set; }
        public virtual DbSet<Orderdetails> Orderdetails { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Questiontypes> Questiontypes { get; set; }
        public virtual DbSet<Questionmedias> Questionmedias { get; set; }
        public virtual DbSet<Declarationdetails> Declarationdetails { get; set; }
        public virtual DbSet<Declarations> Declarations { get; set; }
        public virtual DbSet<Logistics> Logistics { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Atmcodes> Atmcodes { get; set; }
        public virtual DbSet<Outofnotices> Outofnotices { get; set; }
        public virtual DbSet<Purchasecodes> Purchasecodes { get; set; }
        public virtual DbSet<Purchasedetails> Purchasedetails { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
        public virtual DbSet<Warehousestocks> Warehousestocks { get; set; }
        public virtual DbSet<Orderdetailstocks> Orderdetailstocks { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Newmedias> Newmedias { get; set; }
        public virtual DbSet<Preorderdetails> Preorderdetails { get; set; }
        public virtual DbSet<Preorders> Preorders { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Sms> Sms { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Smsdetails> Smsdetails { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<Setproducts> Setproducts { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Returncodes> Returncodes { get; set; }
        public virtual DbSet<Promoteproducts> Promoteproducts { get; set; }
        public virtual DbSet<Promotes> Promotes { get; set; }
        public virtual DbSet<Viewlogs> Viewlogs { get; set; }
        public virtual DbSet<Eventphotos> Eventphotos { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Expenditurecodes> Expenditurecodes { get; set; }
        public virtual DbSet<Expendituredetails> Expendituredetails { get; set; }
        public virtual DbSet<Outcomecodes> Outcomecodes { get; set; }
        public virtual DbSet<Exchanges> Exchanges { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<Refoundcodes> Refoundcodes { get; set; }
        public virtual DbSet<Refounds> Refounds { get; set; }
        public virtual DbSet<Incomecodes> Incomecodes { get; set; }
        public virtual DbSet<Incomes> Incomes { get; set; }
        public virtual DbSet<Invoicecodes> Invoicecodes { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Lims> Lims { get; set; }
        public virtual DbSet<Returns> Returns { get; set; }
        public virtual DbSet<Invoicedetails> Invoicedetails { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Knowledgemedias> Knowledgemedias { get; set; }
        public virtual DbSet<Knowledges> Knowledges { get; set; }
        public virtual DbSet<Accountings> Accountings { get; set; }
        public virtual DbSet<Returndetails> Returndetails { get; set; }
        public virtual DbSet<Expenditures> Expenditures { get; set; }
        public virtual DbSet<Outcomes> Outcomes { get; set; }
        public virtual DbSet<GlobalMyB2B> GlobalMyB2B { get; set; }
    }
}
