//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewlogs
    {
        public System.Guid viewlogid { get; set; }
        public string sessionid { get; set; }
        public string referrersessionid { get; set; }
        public Nullable<System.Guid> memberid { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string browser { get; set; }
        public string platform { get; set; }
        public string url { get; set; }
        public string referrerdns { get; set; }
        public string referrerurl { get; set; }
        public System.DateTime createdate { get; set; }
        public string device { get; set; }
    }
}
