//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehousestocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehousestocks()
        {
            this.Orderdetailstocks = new HashSet<Orderdetailstocks>();
        }
    
        public System.Guid warehousestockid { get; set; }
        public System.Guid warehouseid { get; set; }
        public System.Guid stockid { get; set; }
        public int quantity { get; set; }
        public int quantity_left { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime transdate { get; set; }
        public string memo { get; set; }
    
        public virtual Warehouses Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetailstocks> Orderdetailstocks { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
